### ISSUE TITLE
Há como fazer o aplicativo funcionar no Chrome, não apenas no Android?

### ISSUE THREAD

**Issue by gusbemacbe** [rocketseat-education/nlw-06-flutter#4]
Boa noite, @gabuldev !

Eu gostava que o aplicativo fosse global. Mas no seu projeto, Firebase funciona apenas com Android. Depurei o aplicativo sempre com Chrome ao invés do emulador de Android. 

Há como fazer que Firebase seja global, ou seja, multiplataforma, não apenas no Android para eu não depender do emulador de Android no meu Linux?

Obrigado pela ajuda, atenção, compreensão e paciência!

**Comment by gabuldev** [comment]
Não tem como deixar o firebase global ainda, para cada plataforma precisa configurar. Para você configurar no Flutter web siga essa documentação https://firebase.flutter.dev/docs/installation/web

**Comment by gusbemacbe** [comment]
Tena koutou @gabuldev!

Obrigado por ter indicado esta documentacão. Funcionou no Chrome, mas não consegui clicar na caixa de entrar com a conta da Google. Testei no teu projeto original e deu o mesmo erro.

**Comment by felipecastrosales** [comment]
@gusbemacbe, o ideal é o app sendo usado no Mobile. 
O MLKIt, por exemplo, não tem suporte ao Web e Desktop ainda, vamos aguardar as novidades! 💜

**Comment by gusbemacbe** [comment]
Boa noite, @felipecastrosales!

OK, obrigado pela informação. Vi e entendi o que é ML Kit. 

Estaremos a esperar o lançamento do suporte de ML Kit ao _desktop_ e à _web_.
